/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author hecto
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public menu() {
        initComponents();
        setLocationRelativeTo(null);
        
        try {
            initUsers();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Sucedio un error inesperado. Cierre y vuelva a ejecutar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        registroUsuarios = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Menu de inicios");

        login.setText("Iniciar sesion");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        registroUsuarios.setText("Registro de Usuarios");
        registroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroUsuariosActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(login)
                    .addComponent(registroUsuarios)
                    .addComponent(salir))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registroUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salir)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    Formato de dataBade.db
    
    String Nombre Completo
    int puntos
    long Fecha de creacion
    String username
    String password
    int cartas
    */
    
    private void initUsers() throws IOException{
        //Inicializa los booleanos que usaremos para verificar si los usuarios predeterminados estan en el archivo
        boolean p1 = false, p2 = false, p3 = false , p4 = false;
        
        //Setea el archvio en el que vamos a escribir los usuarios por default
        creacionDeUsuarios.dataBase = new RandomAccessFile("dataBase.db", "rw");
        //Asegura el puntero
        creacionDeUsuarios.dataBase.seek(0);
        
        //Recorrido del archivo
        while (creacionDeUsuarios.dataBase.getFilePointer() < creacionDeUsuarios.dataBase.length()){
            creacionDeUsuarios.dataBase.readUTF(); //Mueve el puntero la cantidad de Bytes que abarque el Nombre Completo del user
            creacionDeUsuarios.dataBase.skipBytes(12); //Skip 4 (int puntos) + 8 (long fecha) = 12 bytes
            
            //Verifica que los defaults esten en el archivo, si es el caso, su respectivo booleano se actualiza a true
            
            switch ((String)creacionDeUsuarios.dataBase.readUTF()){
                case "p1":
                    p1 = true;
                    break;
                case "p2":
                    p2 = true;
                    break;
                case "p3":
                    p3 = true;
                    break;
                case "p4":
                    p4 = true;
                    break;
            }
            
            creacionDeUsuarios.dataBase.readUTF(); //Mueve el puntero la cantidad de Bytes que abarque el password del usuario
        }
        
        menuPrincipal.jugadores = new ArrayList<>();
        
        //Condiciones que suman el usuario por default a la base de datos si este no existe ya
        if (!p1){
            creacionDeUsuarios.addUser("Player 1", "p1", "p1");
            menuPrincipal.jugadores.add(new HumanSequencePlayer (1, "p1"));
        }
        
        if (!p2){
            creacionDeUsuarios.addUser("Player 2", "p2", "p2");
            menuPrincipal.jugadores.add(new HumanSequencePlayer (2, "p2"));
        }
        
        if (!p3){
            creacionDeUsuarios.addUser("Player 3", "p3", "p3");
            menuPrincipal.jugadores.add(new HumanSequencePlayer (3, "p3"));
        }
        
        if (!p4){
            creacionDeUsuarios.addUser("Player 4", "p4", "p4");
            menuPrincipal.jugadores.add(new HumanSequencePlayer (4, "p4"));
        }

    }
    
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        login login = new login();
        setVisible(false);
        
        login.setVisible(true);
        login.setLocationRelativeTo(null);
    }//GEN-LAST:event_loginActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void registroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroUsuariosActionPerformed
        creacionDeUsuarios crear = new creacionDeUsuarios();
        setVisible(false);
        
        crear.setVisible(true);
        crear.setLocationRelativeTo(null);
    }//GEN-LAST:event_registroUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JButton registroUsuarios;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
